name: Run SCA scan with Snyk

on: 
  push

jobs:
  Snykscan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Step 3: Set JAVA_HOME
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      # Step 4: Build the code
      - name: Build the code 
        run: mvn package

      # Step 5: Run Snyk scan
      - name: Run Snyk scan 
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          JAVA_HOME: ${{ env.JAVA_HOME }}  # Ensure JAVA_HOME is passed to Snyk scan
