name: Run SCA scan with Snyk

on:
  push:

jobs:
  Snykscan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # use 'temurin' instead of 'adopt'

    - name: Build the code
      run: mvn package

    - name: Run Snyk scan
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
