name: CI using  maven and jenkins
on:
  push: # run on every commit
  workflow_dispatch:  #run the workflow manually

jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code on the ubuntu server
        uses: action/checkout@v4
      - name: Install Java and Maven on the Ubuntu server
        uses: actions/setup-java@v4
        with:
           distribution: 'temurin'
           java-version: '11'
           cache: 'maven'

      - name: Test the code
        run: mvn test
      - name: Build the code
        run: mvn package
      - name: Get the artifact and uplaod on github repo
        uses: actions/upload-artifact@v4
        with:
        name: java-example-artifact
        path: /home/runner/work/MavenBuild-SL/MavenBuild-SL/target/java-example.war
